name: OP Test Script

on:
    workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Echo Environment Variables
        run: |
            echo "DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN"
            echo "WEBHOOK_URL: $WEBHOOK_URL"
            echo "CHANNEL_ID: $CHANNEL_ID"

      - name: Run script
        env:
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
            CHANNEL_ID: ${{ secrets.CHANNEL_ID }} 
        run: node discord_bot.mjs
